### ISSUE TITLE
More documentation and installation/usage instructions?

### ISSUE THREAD

**Issue by laurelin88** [peterk/munin-indexer#19]
Hi, just wanted to suggest that a little bit more documentation and more detailed instructions would help a lot, especially those that are only getting familiar with using command-line tools. Cheers and thanks!

**Comment by peterk** [comment]
Thx! I will see if I can work on instructions a little bit more this weekend. Anything in particular that could help you get started? Is setting up the prerequisites (docker etc) the problem?

**Comment by laurelin88** [comment]
Thank you for responding!
I started building the docker images and up until a point it went smoothly, until I got an error about psycopg2 
[error_munin.txt](https://github.com/peterk/munin-indexer/files/4594933/error_munin.txt)

Absolute noob here, so can't really tell why this went wrong or how to fix it : )

Plus, I did not change any of the settings for the env_file because I was not sure what would be important or necessary to change, so if you think something is important to configure there I would really appreciate a heads up!
