### ISSUE TITLE
Exception displaying in web interface with "View site"

### ISSUE THREAD

**Issue by machawk1** [peterk/munin-indexer#6]
Using current master f59346b8c5feae7571f5564878a8a39504b1d259, I have "started everything", "set up a super user", and access the web interface at http://0.0.0.0:4444/admin.

Clicking the `VIEW SITE` link near the top of the web interface shows an HTML page displaying a Python exception.

<img width="1136" alt="screen shot 2018-12-09 at 3 06 24 pm" src="https://user-images.githubusercontent.com/2514780/49702251-1b00d000-fbc4-11e8-95c9-5f7ecb264f7d.png">

**Comment by peterk** [comment]
Thx! Looks like a bug that will appear when there is no data. Will add some checks.
